---
title: "Inorganic Chemicals Time Series Plots"
output:
  word_document:
    reference_docx: "blank.docx" # temp version created on download
params:
  word_graphs: NA
  chems: NA
  wells: NA
  frac_filter: NA
  date_range: NA
  rendered_by_shiny: NA
---


```{r, include = FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(knitr)

# data from params ----------------------
word_graphs <- params$word_graphs
chems <- params$chems
wells <- params$wells
frac_filter <- params$frac_filter
date_range <- params$date_range


# dates ---------------------------
# date_format_dmy <- "%d %B %Y" # e.g 11 January 2013
date_format_mdy <- "%b %d, %Y" # e.g Jan 11 2013

# names for selected chems ---------------------
selected_chems <- set_names(chems)

# chunk options
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.ext = 'AGG',
  dpi = 300
)
```


# Data filters
This report is filtered to only include:

* These wells: **`r combine_words(wells, sep = ", ")`** 
* Results from **`r format(as.Date(date_range[1]), date_format_mdy)`** to **`r format(as.Date(date_range[2]), date_format_mdy)`**
* Fraction: **`r params$frac_filter`**

# Graph notes

* When only the year is shown in the x-axis label, this represents the start of the year.

\newpage


# Inorganic chemical summaries


```{r test_plots, results='asis', fig.width=8, fig.height=8}

print_graphs <- function(x, prog){
  cat('\n\n##', selected_chems[x], '\n')
  print(word_graphs[[x]])

  if(params$rendered_by_shiny){
    incProgress(prog) # shiny progress
  }
}


walk(1:length(selected_chems), ~print_graphs(.x, 1/length(selected_chems)))

```





